[package]
name = "lexer_automata"
version = "0.1.0"
edition = "2021"
authors = ["Scriptum Team"]
license = "MIT"

[lib]
name = "lexer_automata"
crate-type = ["lib"]

[dependencies]
unicode-ident = "1.0"

[dev-dependencies]
# Nenhuma dependencia externa adicional: os testes utilizam apenas std.
