[package]
name = "scriptum-codegen"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
scriptum-ast = { path = "../ast" }
scriptum-utils = { path = "../utils" }
smallvec.workspace = true
serde.workspace = true
