[package]
name = "exemplum"
version = "0.1.0"
edition = "2025"

[toolchain]
version = ">=0.1"

[scripts]
build = "scriptum build src/main.stm"
test  = "cargo test -q"
run   = "scriptum run target/main.sbc"
