[package]
name = "scriptum-runtime"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
scriptum-utils = { path = "../utils" }
scriptum-ast = { path = "../ast" }
smallvec.workspace = true
thiserror.workspace = true
